# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CandleChartTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CandleChartTest

  pod 'SwiftCharts', '~> 0.6.5'
  target 'CandleChartTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CandleChartTestUITests' do
    # Pods for testing
  end

end
